___
# Data Quality : Solving Bathroom texts
___

### NOTE: warnings produced by code can be ignored

\
## Step 1 import libraries

In [23]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import sklearn
pd.set_option("display.max_columns", None)
import missingno as msno

## Step 2 Run code to get to standard state of "listings_reduced"

In [34]:
listings=pd.read_csv("https://raw.githubusercontent.com/rickfontenot/airbnb/main/airbnb_nyc_listings.csv?token=ARN5NNHQQO5DGH6T72FBV2DBGD342")

In [35]:
# reducing listings to listings reduced column ref airbnb_eda by Rick

listings_reduced = listings[['id', 'host_id', 
       'host_name', 'host_since', 
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month']]

listings_reduced.head()

,id,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,2845,Jennifer,2008-09-09,NaN,NaN,NaN,f,Midtown,6.0,6.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"New York, United States",Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,NaN,1 bath,NaN,1.0,"[""Essentials"", ""Extra pillows and blankets"", ""...",$150.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,6,36,66,341,48,0,0,2009-11-21,2019-11-04,4.70,4.72,4.62,4.76,4.79,4.86,4.41,NaN,f,3,3,0,0,0.34
1,3831,4869,LisaRoxanne,2008-12-07,within a day,50%,88%,f,Clinton Hill,1.0,1.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"Brooklyn, New York, United States",Bedford-Stuyvesant,Brooklyn,40.68494,-73.95765,Entire guest suite,Entire home/apt,3,NaN,1 bath,1.0,3.0,"[""Essentials"", ""TV with standard cable"", ""Baby...",$75.00,1,730,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,0,1,7,212,408,68,0,2015-01-05,2021-06-29,4.46,4.59,4.50,4.79,4.81,4.72,4.65,NaN,f,1,1,0,0,5.09
2,5121,7356,Garon,2009-02-03,within a day,100%,NaN,f,Bedford-Stuyvesant,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,NaN,NaN,1.0,1.0,"[""Long term stays allowed"", ""Air conditioning""...",$60.00,30,730,30.0,30.0,730.0,730.0,30.0,730.0,t,30,60,90,365,50,0,0,2014-01-22,2016-06-05,4.52,4.22,4.09,4.91,4.91,4.47,4.52,NaN,f,1,0,1,0,0.55
3,5136,7378,Rebecca,2009-02-03,within a day,88%,33%,f,Greenwood Heights,1.0,1.0,"['email', 'phone', 'reviews']",t,t,NaN,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,NaN,1.5 baths,2.0,2.0,"[""TV with standard cable"", ""Long term stays al...",$275.00,5,1125,5.0,5.0,1125.0,1125.0,5.0,1125.0,t,7,9,9,184,1,0,0,2014-01-02,2014-01-02,5.00,5.00,5.00,5.00,5.00,4.00,5.00,NaN,f,1,1,0,0,0.01
4,5178,8967,Shunichi,2009-03-03,within an hour,100%,100%,f,Hell's Kitchen,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,"New York, United States",Midtown,Manhattan,40.76457,-73.98317,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Essentials"", ""Free street parking"", ""TV"", ""W...",$61.00,2,14,2.0,2.0,14.0,14.0,2.0,14.0,t,3,7,14,255,485,12,4,2010-08-18,2021-07-18,4.20,4.19,3.71,4.65,4.40,4.86,4.35,NaN,f,1,0,1,0,3.63

In [36]:
#drop bathrooms and licence, all values missing ref airbnb_eda by Rick

listings_reduced.drop(['bathrooms', 'license'], axis=1, inplace=True)

C:\Users\Joey\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

___
## Step 2 work on Bathroom Texts
___

### Create list of unique values in 'bathroom_texts'

In [37]:
bathroom_texts_list = listings_reduced['bathrooms_text'].unique()

print(bathroom_texts_list)

['1 bath' nan '1.5 baths' '1 shared bath' '1 private bath'
 'Shared half-bath' '2 baths' '1.5 shared baths' '3 baths' 'Half-bath'
 '2.5 baths' '2 shared baths' '0 baths' '4 baths' '0 shared baths'
 'Private half-bath' '4.5 baths' '5.5 baths' '2.5 shared baths'
 '3.5 baths' '15.5 baths' '5 baths' '3 shared baths' '4 shared baths'
 '6 baths' '3.5 shared baths' '6 shared baths' '6.5 shared baths'
 '4.5 shared baths' '5.5 shared baths' '7.5 baths' '5 shared baths'
 '6.5 baths' '8 baths' '7 shared baths' '7 baths' '10 baths']

### Make nan into string -> 'NA'

In order for the the dictionary of terms I'm going to create it I found it necessary to make NA into a string 'NA'

Later I will change them back

In [38]:
#convert NA values to 'NA'
listings_reduced['bathrooms_text'] = listings_reduced['bathrooms_text'].astype(object).replace(np.nan, 'NA')

<ipython-input-38-1735bd9041bb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_reduced['bathrooms_text'] = listings_reduced['bathrooms_text'].astype(object).replace(np.nan, 'NA')

### Create dictionary of terms from Unique values 


In this step I doing several things. 
1) the NA term must string -> 'NA' \
2) half bath /  private half bath entries now have a numeric lead of 0.5 (even if its still a string value) \
3) I make each entry into private or shared 
>* If bath appears alone I assume it to be private

In [39]:
transdict = {'1 bath': '1 private', 
             'NA': 'NA',
             '1.5 baths': '1.5 private',
             '1 shared bath': '1 shared', 
             '1 private bath': '1 private',
             'Shared half-bath': '0.5 shared',
             '2 baths': '2 private',
             '1.5 shared baths': '1.5 shared',
             '3 baths': '3 private',
             'Half-bath': '0.5 private',
             '2.5 baths': '2.5 private', 
             '2 shared baths': '2 shared',
             '0 baths' : '0 private',
             '4 baths':'4 private', 
             '0 shared baths': '0 shared',
             'Private half-bath': '0.5 private',  
             '4.5 baths' :'4.5 private', 
             '5.5 baths': '5.5 private' , 
             '2.5 shared baths': '2.5 shared',
             '3.5 baths': '3.5 private', 
             '15.5 baths': '15.5 private', 
             '5 baths': '5 private', 
             '3 shared baths': '3 shared', 
             '4 shared baths': '4 shared',
             '6 baths': '6 private', 
             '3.5 shared baths': '3.5 private', 
             '6 shared baths' : '6 shared',
             '6.5 shared baths': '6.5 shared', 
             '4.5 shared baths' :'4.5 private',
             '5.5 shared baths' : '5.5 private', 
             '7.5 baths': '7.5 private', 
             '5 shared baths': '5 shared',
             '6.5 baths': '6.5 private', 
             '8 baths': '8 private', 
             '7 shared baths':'7 shared', 
             '7 baths': '7 private', 
             '10 baths': '10 private'}

In [40]:
#use trandict to iterate over bathrooms_text column

listings_reduced['bathrooms_text'] = [transdict[letter] for letter in listings_reduced['bathrooms_text']]

<ipython-input-40-2ca79fabf47c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_reduced['bathrooms_text'] = [transdict[letter] for letter in listings_reduced['bathrooms_text']]

In [42]:
# use str.split to create two new columns 'num_baths' and 'bath_type'
listings_reduced[['num_baths','bath_type']] = listings_reduced['bathrooms_text'].str.split(' ', 1, expand = True)

C:\Users\Joey\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [43]:
#check work
listings_reduced.head(100)

,id,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,num_baths,bath_type
0,2595,2845,Jennifer,2008-09-09,NaN,NaN,NaN,f,Midtown,6.0,6.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"New York, United States",Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,1 private,NaN,1.0,"[""Essentials"", ""Extra pillows and blankets"", ""...",$150.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,6,36,66,341,48,0,0,2009-11-21,2019-11-04,4.70,4.72,4.62,4.76,4.79,4.86,4.41,f,3,3,0,0,0.34,1,private
1,3831,4869,LisaRoxanne,2008-12-07,within a day,50%,88%,f,Clinton Hill,1.0,1.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"Brooklyn, New York, United States",Bedford-Stuyvesant,Brooklyn,40.68494,-73.95765,Entire guest suite,Entire home/apt,3,1 private,1.0,3.0,"[""Essentials"", ""TV with standard cable"", ""Baby...",$75.00,1,730,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,0,1,7,212,408,68,0,2015-01-05,2021-06-29,4.46,4.59,4.50,4.79,4.81,4.72,4.65,f,1,1,0,0,5.09,1,private
2,5121,7356,Garon,2009-02-03,within a day,100%,NaN,f,Bedford-Stuyvesant,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,NA,1.0,1.0,"[""Long term stays allowed"", ""Air conditioning""...",$60.00,30,730,30.0,30.0,730.0,730.0,30.0,730.0,t,30,60,90,365,50,0,0,2014-01-22,2016-06-05,4.52,4.22,4.09,4.91,4.91,4.47,4.52,f,1,0,1,0,0.55,NA,None
3,5136,7378,Rebecca,2009-02-03,within a day,88%,33%,f,Greenwood Heights,1.0,1.0,"['email', 'phone', 'reviews']",t,t,NaN,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,1.5 private,2.0,2.0,"[""TV with standard cable"", ""Long term stays al...",$275.00,5,1125,5.0,5.0,1125.0,1125.0,5.0,1125.0,t,7,9,9,184,1,0,0,2014-01-02,2014-01-02,5.00,5.00,5.00,5.00,5.00,4.00,5.00,f,1,1,0,0,0.01,1.5,private
4,5178,8967,Shunichi,2009-03-03,within an hour,100%,100%,f,Hell's Kitchen,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,"New York, United States",Midtown,Manhattan,40.76457,-73.98317,Private room in rental unit,Private room,2,1 private,1.0,1.0,"[""Essentials"", ""Free street parking"", ""TV"", ""W...",$61.00,2,14,2.0,2.0,14.0,14.0,2.0,14.0,t,3,7,14,255,485,12,4,2010-08-18,2021-07-18,4.20,4.19,3.71,4.65,4.40,4.86,4.35,f,1,0,1,0,3.63,1,private
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,44973,198411,Anastasia,2010-08-11,within an hour,100%,88%,f,Williamsburg,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'kba...",t,t,"Brooklyn, New York, United States",Williamsburg,Brooklyn,40.70894,-73.95234,Entire rental unit,Entire home/apt,2,1 private,NaN,0.0,"[""Essentials"", ""Extra pillows and blankets"", ""...",$98.00,30,180,30.0,30.0,180.0,180.0,30.0,180.0,t,1,1,1,153,122,1,1,2012-05-27,2021-07-31,4.63,4.83,4.71,4.85,4.93,4.52,4.68,f,1,1,0,0,1.09,1,private
96,45542,202249,Campbell,2010-08-15,NaN,NaN,NaN,f,Harlem,1.0,1.0,['phone'],t,f,"New York, United States",Harlem,Manhattan,40.82569,-73.93842,Entire rental unit,Entire home/apt,4,1 private,2.0,2.0,"[""Essentials"", ""Free street parking"", ""Long te...",$100.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,0,0,0,0,18,0,0,2018-10-19,2018-12-13,4.78,4.83,4.56,5.00,4.83,4.44,4.67,f,1,1,0,0,0.53,1,private
97,45556,67778,Doug,2010-01-04,within an hour,100%,100%,t,Fort Greene,3.0,3.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Brooklyn, New York, United States",Fort Greene,Brooklyn,40.68834,-73.97578,Private room in townhouse,Private room,2,1.5 shared,1.0,1.0,"[""Essentials"", ""Backyard"", ""EV charger"", ""Extr...",$65.00,2,31,2.0,2.0,31.0,31.0,2.0,31.0,t,4,29,57,147,270,19,5,2014-10-22,2021-08-03,4.89,4.94,4.90,4.94,4.99,4.97,4.82,t,2,0,2,0,3.27,1.5,shared
98,45910,204539,Mark,2010-08-17,within a few hours,90%,40%,t,Ridgewood,5.0,5.0,"['email', 'phone', 'facebook', 'reviews', 'kba']",t,t,NaN,Ridgewood,Queens,40.70309,-73.89963,Entire townhouse,Entire home/apt,16,2.5 private,5.0,10.0,"[""Essentials"", ""TV with standard cable"", ""Free...",$395.00,30,730,30.0,30.0,730.0,730.0,30.0,730.0,t,30,60,90,365,13,0,0,2019-10-29,2019-11-12,4.42,4.64,4.36,4.82,5.00,4.82,4.55,f,6,5,1,0,0.60,2.5,private
99,45935,204586,L,2010-08-17,NaN,NaN,NaN,f,NaN,1.0,1.0,"['email', 'phone']",t,f,NaN,Mott Haven,Bronx,40.80635,-73.92201,Private room in rental unit,Private room,1,1 shared,1.0,1.0,"[""Essentials"", ""Long term stays allowed"", ""Fir...",$60.00,30,40,30.0,30.0,40.0,40.0,30.0,40.0,t,24,54,83,83,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN,1,shared

___
### Step 3: Force num_baths to become float
___

In [52]:
#convert 'NA' values to nan
listings_reduced['num_baths'] = listings_reduced['num_baths'].astype(object).replace( 'NA',np.nan)

<ipython-input-52-466ba1a83d13>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_reduced['num_baths'] = listings_reduced['num_baths'].astype(object).replace( 'NA',np.nan)

In [54]:
listings_reduced['num_baths'] = listings_reduced['num_baths'].astype(np.float16)

<ipython-input-54-a6cf4d54851e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_reduced['num_baths'] = listings_reduced['num_baths'].astype(np.float16)

___
### Step: 4 Force bath_type to become category
___

In [63]:
#convert None values to nan
listings_reduced.bath_type.fillna(value=np.nan, inplace=True)

C:\Users\Joey\anaconda3\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [65]:
listings_reduced['bath_type'] = listings_reduced['bath_type'].astype('category')

<ipython-input-65-47eecb241410>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_reduced['bath_type'] = listings_reduced['bath_type'].astype('category')

___
### Final Step: check work and ensure it is the data type we want 
___

In [66]:
listings_reduced.dtypes

id                                                 int64
host_id                                            int64
host_name                                         object
host_since                                        object
host_response_time                                object
host_response_rate                                object
host_acceptance_rate                              object
host_is_superhost                                 object
host_neighbourhood                                object
host_listings_count                              float64
host_total_listings_count                        float64
host_verifications                                object
host_has_profile_pic                              object
host_identity_verified                            object
neighbourhood                                     object
neighbourhood_cleansed                            object
neighbourhood_group_cleansed                      object
latitude                                         float64
longitude                                        float64
property_type                                     object
room_type                                         object
accommodates                                       int64
bathrooms_text                                    object
bedrooms                                         float64
beds                                             float64
amenities                                         object
price                                             object
minimum_nights                                     int64
maximum_nights                                     int64
minimum_minimum_nights                           float64
maximum_minimum_nights                           float64
minimum_maximum_nights                           float64
maximum_maximum_nights                           float64
minimum_nights_avg_ntm                           float64
maximum_nights_avg_ntm                           float64
has_availability                                  object
availability_30                                    int64
availability_60                                    int64
availability_90                                    int64
availability_365                                   int64
number_of_reviews                                  int64
number_of_reviews_ltm                              int64
number_of_reviews_l30d                             int64
first_review                                      object
last_review                                       object
review_scores_rating                             float64
review_scores_accuracy                           float64
review_scores_cleanliness                        float64
review_scores_checkin                            float64
review_scores_communication                      float64
review_scores_location                           float64
review_scores_value                              float64
instant_bookable                                  object
calculated_host_listings_count                     int64
calculated_host_listings_count_entire_homes        int64
calculated_host_listings_count_private_rooms       int64
calculated_host_listings_count_shared_rooms        int64
reviews_per_month                                float64
num_baths                                        float16
bath_type                                       category
dtype: object

In [67]:
num_baths_list = listings_reduced['num_baths'].unique()
bath_type_list = listings_reduced['bath_type'].unique()

print(num_baths_list)
print(bath_type_list)

[ 1.   nan  1.5  0.5  2.   3.   2.5  0.   4.   4.5  5.5  3.5 15.5  5.
  6.   6.5  7.5  8.   7.  10. ]
['private', NaN, 'shared']
Categories (2, object): ['private', 'shared']